pdf/urls.py
from django.urls import path
from django.urls import re_path as url
from . import views

app_name = 'pdf'

urlpatterns = [
    url(r'^export/(?P<exam_id>[-\w]+)/a/$', views.exportPDFa, name='exam_export'),
    url(r'^export/(?P<exam_id>[-\w]+)/b/$', views.exportPDFb, name='exam_export_b'),
]

questions/urls.py
from django.urls import path
from .views import (exam_detail_update, 
                        ExamListView, 
                        exam_detail,
                        ArchivedExamListView,
                        archive_exam
                        )

app_name = 'quiz'

urlpatterns = [
    path('', ExamListView.as_view(), name='exam_list'),
    path('archived/', ArchivedExamListView.as_view(), name='archived_exam_list'),
    path('<int:exam_id>/archive_exam/', archive_exam, name='archive_exam'),
    path('<int:exam_id>/duzenle/', exam_detail_update, name='exam_detail_update'),
    path('<int:exam_id>/', exam_detail, name='exam_detail'),
    
]

quiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from questions.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('quiz/', include('questions.urls')),
    path('pdf/', include('pdf.urls', namespace='pdf')),
    path('', HomeView.as_view(), name='home'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/mc/answer_key.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>


<body>
    <p>{{exam}}</p>
    <form method="POST">
        {% csrf_token %}
        
        {{ form.as_p }}        
        <input type="submit">
        
    </form>
</body>
</html>

templates/mc/exam_detail.html
{% extends 'base.html' %}
{% block style %}

ul { list-style-type: none; }
ul:nth-child(even) {background-color:#dddddd;}
.sidenav {
  width: 140px;
  position: fixed;
  z-index: 1;
  top: 200px;
  left: 10px;
  background: #eee;
  overflow-x: hidden;
  padding: 8px 0;
}

.sidenav li {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 16px;
  /*color: #2196F3;*/
  display: block;
}

.sidenav a:hover {
  color: #064579;
}

.main {
  margin-left: 160px; /* Same width as the sidebar + left position in px */
  padding: 0px 10px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}

{% endblock %}

{% block title %}Exam Detail{% endblock %}

{% block content %}
<div class="sidenav bg-light">
  <ul class="list-group">
    <li class="list-group-item"><a href="{% url 'quiz:exam_detail_update' exam.pk %}">Düzenle</a></li>
    <li class="list-group-item"><a href="{% url 'pdf:exam_export' exam.pk %}">PDF A Kitapçığı</a></li>
    <li class="list-group-item"><a href="{% url 'pdf:exam_export_b' exam.pk %}">PDF B Kitapçığı</a></li>
  </ul>
</div>
<div class="main"> 
    <h4>{{ exam.semester }} - YDL{{ exam.ydl }} - {{ exam.exam }}- {{exam.session}}. Oturum - Raw Hali</h4>
    <p>Cevapları karıştırmak için soldan A Kitapçığı ve B kitapçığı linklerine tıklayabilirsiniz.</p>
    {% for q in question %}
  <div class="card">
    <div class="card-header">
    <p style="display:inline">{{forloop.counter}}.{{ q.question|linebreaks }}</p>
    </div>
    <div class="card-body">
      <ol type="a">
        <li>{{q.option1}}</li>
        <li>{{q.option2}}</li>
        <li>{{q.option3}}</li>
        <li>{{q.option4}}</li>
      </ol>
    </div>
    
  </div>
  {% endfor %} 
  
</div>
{% endblock %}

templates/mc/exam_detail_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block style %}
.sidenav {
    width: 110px;
    position: fixed;
    z-index: 1;
    top: 55px;
    left: 10px;
    background: white;
    overflow-x: hidden;
    padding: 8px 0;
  }
  
.sidenav li {
    padding: 6px 8px 6px 16px;
    text-decoration: none;
    font-size: 16px;
    /*color: #2196F3;
    display: block;*/
  }
  
.sidenav a:hover {
    color: #064579;
  }
.main {
    margin-left: 160px; /* Same width as the sidebar + left position in px */
    padding: 0px 10px;
}
.cardish {
    width: 800px;
}
{% endblock %}
{% block content %}

<div class="main">
    <form method="POST" class="bootstrap4">
        {% csrf_token %}
        <div class="sidenav bg-light">
            <ul class="list-group">
                <span class="no-button-class">
                    <span>
                        <li class="list-group-item"><button type="submit" class="btn btn-primary">Kaydet</button></li>
                    </span>
                </span>
            </ul>
          </div>
        <div class="cardish">
        <h3>{{ exam }}. Oturum</h3>
        {{ formset|crispy }}
        </div>
        
        <br/>
    </form>
</div>
{% endblock %}

templates/mc/exam_detail_update2.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block style %}
.sidenav {
    width: 110px;
    position: fixed;
    z-index: 1;
    top: 55px;
    left: 10px;
    background: white;
    overflow-x: hidden;
    padding: 8px 0;
  }
  
.sidenav li {
    padding: 6px 8px 6px 16px;
    text-decoration: none;
    font-size: 16px;
    /*color: #2196F3;
    display: block;*/
  }
  
.sidenav a:hover {
    color: #064579;
  }
.main {
    margin-left: 160px; /* Same width as the sidebar + left position in px */
    padding: 0px 10px;
}
.card {
    width: 800px;
}
{% endblock %}
{% block content %}
 
<div class="main">
    <form method="POST" class="form-horizontal" role="form">
        {% csrf_token %}
        {{ formset.management_form }}
        <div class="sidenav bg-light">
            <ul class="list-group">
                <span class="no-button-class">
                    <span>
                        <li class="list-group-item"><input type="submit" class="btn btn-primary" value="Kaydet"></input></li>
                    </span>
                </span>
            </ul>
          </div>
        
        {% for f in formset %}
        {% for field in f %}
            <div class="form-group">
                
                <div class="col-sm-10">
                    <div class="container">
                        <div class="row">
                            <div class="col">
                                <h5>{{forloop.counter}}{{field.question}}</h5>
                            </div>
                            <div class="col">

                                <p>a. {{field.option1}}</p>
                                <p>b. {{field.option2}}</p>
                                <p>c. {{field.option3}}</p>
                                <p>d. {{field.option4}}</p>
                                <p>{{field.columns}}</p>
                                
                            </div>
                            <div>
                                {% for hidden in form.hidden_fields %}
                                    {{ hidden }}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% endfor %}
        <input type="submit">
        <br/>
    </form>
</div>
{% endblock %}

templates/mc/exam_list.html
{% extends 'base.html' %}

{% block style %}
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}
  
td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}
  
tr:nth-child(even) {
    background-color: #dddddd;
}
{% endblock %}

{% block title %}Quiz List{% endblock %}

{% block content %}

    
    <div align="center">
    <table style="width:80%">
        <tr>
            <th>Sınav Adı</th>
            <th>İncele</th>
            <th>Düzenle</th>
            <th>A Kitapçığı</th>
            <th>B Kitapçığı</th>
            <th>Arşivle</th>
        </tr>
        {% for exam in exams %}
        <tr>
            {% if exam.ydl == "185L" or exam.ydl == "186L" %}
                <td>{{exam.semester}} YDL{{exam.ydl}}isans {{exam.exam}} {{exam.session}}.Oturum</td>
            {% elif exam.ydl == "185" or exam.ydl == "186" %}
                <td>{{exam.semester}} YDL{{exam.ydl}} Önlisans {{exam.exam}} {{exam.session}}.Oturum</td>
            {% else %}
                <td>{{exam.semester}} YDL{{exam.ydl}} {{exam.exam}} {{exam.session}}.Oturum</td>
            {% endif %}
            <td><a class="btn btn-primary" href="{% url 'quiz:exam_detail' exam.pk %}">İncele</a></td> 
            <td><a class="btn btn-primary" href="{% url 'quiz:exam_detail_update' exam.pk %}">Düzenle</a></td> 
            <td><a class="btn btn-success" href="{% url 'pdf:exam_export' exam.pk %}">A Kitapçığı</a></td> 
            <td><a class="btn btn-success" href="{% url 'pdf:exam_export_b' exam.pk %}">B Kitapçığı</a></td> 
            <td><a class="btn btn-success" id="archive_button" href="{% url 'quiz:archive_exam' exam.pk %}">Arşivle</a></td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}