pdf/urls.py
from django.urls import path
from django.urls import re_path as url
from . import views

app_name = 'pdf'

urlpatterns = [
    url(r'^export/(?P<exam_id>[-\w]+)/a/$', views.exportPDFa, name='exam_export'),
    url(r'^export/(?P<exam_id>[-\w]+)/b/$', views.exportPDFb, name='exam_export_b'),
]

questions/urls.py
from django.urls import path
from .views import (exam_detail_update, 
                        ExamListView, 
                        exam_detail,
                        ArchivedExamListView,
                        archive_exam
                        )

app_name = 'quiz'

urlpatterns = [
    path('', ExamListView.as_view(), name='exam_list'),
    path('archived/', ArchivedExamListView.as_view(), name='archived_exam_list'),
    path('<int:exam_id>/archive_exam/', archive_exam, name='archive_exam'),
    path('<int:exam_id>/duzenle/', exam_detail_update, name='exam_detail_update'),
    path('<int:exam_id>/', exam_detail, name='exam_detail'),
    
]

quiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from questions.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('quiz/', include('questions.urls')),
    path('pdf/', include('pdf.urls', namespace='pdf')),
    path('', HomeView.as_view(), name='home'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'questions/styles.css' %}">
    <style>{% block style %}{% endblock %}</style>
    <meta charset="utf-8">
    <title>{% block title %}Quiz Maker{% endblock %}</title>
</head>
<body>
  <main>
      {% include 'navbar.html' %}
      {% block content %}
      {% endblock %}

  </main>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  <div class="card bg-light mb-3 mx-auto" style="max-width: 18rem;">
    <div class="card-header text-center"><p>Merhaba {{ user.username }}!</p></div>
    <div class="card-body text-center">
      <p><a href="{% url 'quiz:exam_list' %}">Tüm Etkin Sınavları Göster</a></p>
      <p><a href="{% url 'logout' %}">Çıkış Yap</a></p>
    </div>
  </div>
{% else %}
    <div class="card bg-light mb-3 mx-auto" style="max-width: 18rem;">
      <div class="card-header text-center">Giriş Yap</div>
      <div class="card-body text-center">
        <p><a href="{% url 'login' %}">Giriş yapmak için tıklayın</a></p>
      </div>
    </div>
  

{% endif %} 

{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home' %}">Quiz Maker</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      {% url 'quiz:exam_detail' id=exam_id as exam_detail %}
      {% url 'quiz:exam_detail_update' as exam_detail_update %}
      {% url 'request.path' as path %}
      {% url 'quiz:exam_list' as exam_list %}
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
        
          {% if request.path == exam_list %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'quiz:archived_exam_list' %}">Arşivlenen Sınavlar</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'quiz:exam_list' %}">Sınav Listesi</a>
            </li>
          {% endif %}
        </ul>
      </div>
      <div class="collapse navbar-collapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Çıkış yap</a>
            </li>
          </ul>
      </div>
            
        {% else %}
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link float-right" href="{% url 'login' %}">Giriş yap</a>
            </li>
          </ul>
        </div>
        {% endif %}
      
    
  </nav>